const CommonConstants = {
	STATUS_SUCCESS : "SUCCESS",
	STATUS_FAILURE : "FAILURE",
	OPERATION_SUCCESS: "SUCCESS",
	OPERATION_FAILURE: "FAILURE",

	/*** Login - Start ***/
	ACTION_LOGIN : "ACTION_LOGIN",
	SERVICE_LOGIN : "user",
	EVENT_LOGIN_FAILURE : "EVENT_LOGIN_FAILURE",
	EVENT_LOGIN_SUCCESS : "EVENT_LOGIN_SUCCESS",
	ACTION_LOGOUT : "ACTION_LOGOUT",
	EVENT_LOGOUT : "EVENT_LOGOUT",
	/*** Login - End ***/

	ACTION_DASHBOARD_DATA : "ACTION_DASHBOARD_DATA",
	SERVICE_DASHBOARD_DATA : "dashboard",
	EVENT_DASHBOARD_DATA_SUCCESS : "EVENT_DASHBOARD_DATA_SUCCESS",
	EVENT_DASHBOARD_DATA_FAILURE : "EVENT_DASHBOARD_DATA_FAILURE",
	ACTION_DASHBOARD_CONFIGURATION : "ACTION_DASHBOARD_CONFIGURATION",
	SERVICE_DASHBOARD_CONFIGURATION : "dashboard",
	EVENT_DASHBOARD_CONFIGURATION_SUCCESS : "EVENT_DASHBOARD_CONFIGURATION_SUCCESS",
	EVENT_DASHBOARD_CONFIGURATION_FAILURE : "EVENT_DASHBOARD_CONFIGURATION_FAILURE",

}

module.exports = CommonConstants;

